version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      app_net:
    restart: unless-stopped
    volumes:
      - ./confs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./confs/certbot/conf:/etc/letsencrypt
      - ./confs/certbot/www:/var/www/certbot
      - ./cv-site:/var/www/cv-site
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
#  certbot:
#    container_name: certbot
#    image: certbot/certbot
#    networks:
#      app_net:
#    restart: unless-stopped
#    volumes:
#      - ./confs/certbot/conf:/etc/letsencrypt
#      - ./confs/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  app_net:
    name: app_net
